name: Robot Framework Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          # Remove existing symlinks if they exist
          sudo rm -f /usr/bin/google-chrome
          sudo rm -f /usr/bin/chromedriver
          # Create new symlinks
          sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install webdriver-manager

      - name: Run tests
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          robot \
            --variable BROWSER:headlesschrome \
            --variable OPTIONS:"--no-sandbox;--disable-dev-shm-usage;--disable-gpu;--remote-debugging-port=9222;--user-data-dir=/tmp/chrome-profile" \
            -d results \
            tests/login_test.robot

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Robot-Results
          path: results/