name: Robot Framework Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install webdriver-manager

      - name: Run tests
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          robot \
            --variable BROWSER:chrome \
            --variable OPTIONS:"--no-sandbox;--disable-dev-shm-usage" \
            -d results \
            tests/

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Robot-Results
          path: results/